MarginallyClever/Makelangelo-software

java/src/Makelangelo/Makelangelo.java
Removed default to Windows so that Linux is also usable. Allows for successful printing on Raspberry Pi among other systems. 
(Tested on Windows 8.1 and Raspbian)
Code referenced: http://www.mkyong.com/java/how-to-detect-os-in-java-systemgetpropertyosname/
=> Allowed for serial connections on Linux

java/src/Makelangelo/LanguageContainer.java
When a newline character `\n` was being read in from the xml files for multilingual support, it was being escaped `\\n` and thus not behaving as an actual newline (see the screenshot below). I updated the method that parses the xml to replace any `\\n` with `\n`.
=> Added a fix for parsing of new line value from xml file.

java/languages/english.xml, java/languages/espanol.xml, java/languages/french.xml, java/languages/italiano.xml, java/src/Makelangelo/Makelangelo.java
After reading @i-make-robots' [comment](https://github.com/MarginallyClever/Makelangelo/pull/61#issuecomment-85517620), I pulled out the hardcoded About Message Dialog's HTML String constant into the translation file.
Because of the dynamic way the HTML is built in the Java code, I had to split the internationalized HTML String in two. I added the key/values to the all the languages, FIXMEs where it is not translated, and documentation as to why the key/values are split up in the Java and XML files.
=> Made About HTML "Internationalizable"

java/pom.xml
Closes #75
This will not be apparent when launching from an IDE
Developers must configure their IDE to use the "-splash:src/main/resources/logo.png" VM option.
=> Added manifest entry for splash screen.

java/pom.xml, java/src/main/assembly/application.xml
This replaces the use of the Maven Assembly plugin's
"jar-with-dependencies" descriptor with a custom descriptor
that places the required native libraries for Windows AMD64/i586,
Linux AMD64/i586, and OS X Universal into the correct place in
the resulting jar file.
See https://jogamp.org/bugzilla/show_bug.cgi?id=845 for details.
=> Add an assembly descriptor that produces a onejar

java/src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
Switched from using Alt to using the OS-appropriate shortcut key for menu shortcuts. This fixes Issue #170.
Apparently Zoom In/Out were the only menu commands with a shortcut key. "Open File" must have had one in an older version.
=> #170 - Used Ctrl/Command instead of Alt

java/src/main/java/com/marginallyclever/makelangeloRobot/settings/PanelAdjustPaper.java
My locale uses commas instead of dots as separator for decimal numbers. Because of this, I was getting the following error when saving a configuration:
```
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "420,0"
at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
at java.lang.Double.parseDouble(Unknown Source)
at java.lang.Double.valueOf(Unknown Source)
at com.marginallyclever.makelangeloRobot.settings.PanelAdjustPaper.save(PanelAdjustPaper.java:291)
...
```
I modified the method after checking how decimal values is handled in other parts of the code.
=> Fix - Decimal handling when saving paper dimensions

src/main/com/marginallyclever/makelangelo/DrawPanel.java, src/main/com/marginallyclever/makelangelo/Makelangelo.java
Makelangelo takes up 160% CPU usage on my MacBook Pro, when it's basically idle. The FPSAnimator which repaints the drawPanel at 20fps is wasting lots of resources. Most of the time nothing has changed and the drawPanel doesn't need to be repainted.
I now reduced the framerate to 1 repaint per second, so the interface will continue to be updated (albeit with slight lag). But I've added explicit calls to repaint() when certain events occur, like dragging the viewport, or zooming. That way, these events will repaint immediately, there won't be any lag, and we won't be constantly repainting when nothing changed.
Ideally the FPSAnimator would be removed completely, and all events (like the manual driving commands) would call repaint().
With the changes in this pull request the CPU usage …
=> Reduce CPU usage

src/main/com/marginallyclever/artPipeline/ArtPipeline.java, src/test/resources/dedupe_test.svg
Hi Dan, I hope you like this pull request.
I was able to optimize further by merging overlapping lines.
New real world drawing time of reorder_test.svg:
`12m8s 4757 / 4757 100.00%`
Compared to previous time:
`16m19s 13193 / 13193 100.00%`
And that's with a lower `EPSILON_CONNECTED` value, meaning actual performance gain is a bit higher still. But I found the current value of 2 to skip too many pen up moves.
If I had kept `EPSILON_CONNECTED` set to 2, then the score would be:
`11m46s 4670 / 4670 100.00%`
I've added a test SVG as well, to demonstrate the benefits.
=> Deduplicate by merging overlapping lines

pom.xml
Hi, 
Thanks for your work.
Here is a fix for maven in order to package the app on a fresh install. The groupId is changed to match the file stored in `java/local-maven-repo/org/kabeja/kabeja/0.4/kabeja-0.4.jar`
Otherwise, it fails with : 
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.641 s
[INFO] Finished at: 2021-08-10T19:41:19+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Makelangelo: Could not resolve dependencies for project com.marginallyclever:Makelangelo:jar:7.24.5: Failed to collect dependencies at net.sourceforge:kabeja:jar:0.4: Failed to …
```
=> Update kabeja groupId according to local repo structure

src/test/com/marginallyclever/makelangelo/MakelangeloTest.java
Hi,
here a small modification to enable MakelangeloTest to be run in the CI: PreferencesHelper and Translator are not needed ti read the version of the software
Regards
=> Remove PreferencesHelper & Translator in MakelangeloTest as they are not needed

src/main/com/marginallyclever/makelangelo/ScaleTurtlePanel.java
I increased the size of the scale window in order to see better the values.
The "lock 🔒" is selected by default, and the button up and down increment by 1 unit instead of 0.1.
Before:
After:
=> Set the "Scale window" larger and select the lock by default

src/main/com/marginallyclever/makelangelo/Makelangelo.java
Taken from https://community.oracle.com/tech/developers/discussion/1356333/closing-a-swing-app-through-menu-file-exit
=> Fire the close event from the Quit menuItem

src/main/com/marginallyclever/makelangelo/Makelangelo.java
unless it was done on purpose not to position the window at the right coordinates for the next launch. ;)
=> Makelangelo JFrame KEY_WINDOW_Y value to "windowY" // was "windowX"

src/main/com/marginallyclever/makelangelo/makeArt/io/LoadFilePanel.java
It seems to me that this permutation must be made. (unless it's normal ... or on purpose.)
Otherwise when you open a recent file and if you use the "Open" button which opens a JFileChooser that you "Cancel", the controls on the panel are no longer usable. 
(and as the image has not changed ... it's disagreeable to have to close the LoadFile dialog to reopen it ...)
=> Fix LoadFilePanel panel frozzen after Open Cancelled.

src/main/com/marginallyclever/makelangelo/Translator.java
To ask the user to select a valid language name if the preference language name does not match a language name value in the language file.
To avoid some null issues in Translator.get(String key)
or else you get this kind of problems :
```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
...
Caused by: java.lang.NullPointerException: Cannot invoke "com.marginallyclever.makelangelo.TranslatorLanguage.get(String)" because the return value of "java.util.Map.get(Object)" is null
at com.marginallyclever.makelangelo.Translator.get(Translator.java:223)
at com.marginallyclever.makelangelo.makeArt.io.vector.LoadScratch3.<init>(LoadScratch3.java:68)
at com.marginallyclever.makelangelo.makeArt.io.vector.TurtleFactory.<clinit>(TurtleFactory.java:13)
```
=> Fix Language name value from preferences no match.

src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
On macos, the menubar can be integrated in the menubar on the top of the screen. 
Here is modification to make a better look and feel.
To move the menubar, an environment variable has only to be set. I also remove the quit menu item only for macos as it is already integrated in the "makelangelo" menu of macos.
Before: 
After:
=> Move menubar to OS X menubar

.github/workflows/maven.yml
I also split the CI into 2 jobs for clarity
Here is the result:
=> Upload the nightly build only on the main repos 

src/main/java/com/marginallyclever/makelangelo/Makelangelo.java, src/main/java/com/marginallyclever/makelangelo/paper/Paper.java
When selecting a small paper size and restarting the app, the viewport is zoomed on paper, and the user is confused.
Here is an example with A4.
Before:
After:
=> Zoom on the machine at startup

src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
Fix #446:
> "robot controls > advanced controls > home" does not unlock draw control buttons
=> Fix #446: unlock draw control buttons when find home button is clicked

src/main/java/com/marginallyclever/makelangelo/Makelangelo.java, src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
Fix the size of the windows to avoid the problem described in #446
> Also, show advanced controls, then drag window bottom downward. tabs to not resize to fill.
=> Fix #446: the robot control window is not resizable anymore

.github/workflows/maven.yml
Upload artifact on every branch and update retention days to 5 in order to be able to download them.
They are not published in the nightly build.
=> Upload artifact on every branch and update retention days to 5

src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/ChooseConnection.java
the button was still enabled when the robot was connected, now it is fixed:
=> 💄 Refresh button disabled when the connect button is clicked

src/main/java/com/marginallyclever/makelangelo/makeArt/InfillTurtleAction.java
to view the possible infil created ...
As in InfillTurtelAction, myMakelangelo.setTurtle indirectly call myTurtleRenderer.setTurtle(turtle); :
https://github.com/MarginallyClever/Makelangelo-software/blob/94745b3e8154a335e397d5a0c5091d6e1e6d78b6/src/main/java/com/marginallyclever/makelangelo/Makelangelo.java#L974-L976
and so the last slider position is updated. ( setLast(size);  line 95 )
https://github.com/MarginallyClever/Makelangelo-software/blob/94745b3e8154a335e397d5a0c5091d6e1e6d78b6/src/main/java/com/marginallyclever/makelangelo/turtle/turtleRenderer/TurtleRenderFacade.java#L89-L96
=> InfillTurtleAction fix to update the preview sliver last max limite

.github/workflows/maven.yml
v2 has been published april 2021, here is the doc: https://github.com/actions/setup-java
Major changes: need to specify the type of jvm and the maven cache can be directly configured
=> 👷 Update github actions/setup-java to v2

.github/workflows/maven.yml
I noticed in the PR https://github.com/MarginallyClever/Makelangelo-software/pull/481 that the CI ran 2 times on different triggers: 
So now, when creating a new branch, either open a pull request to have the CI running or add it to this file if it is a long lived branch like `bugfix-7.31.x`.
=> 👷 Github actions now build only master on the main repo and PR from contributors

src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
Until now, the native menu Makelangelo on macos was not bonded to the app. When clicking on the "about", it will not show the about of Makelangelo but one built in the jvm. 
When quitting the app from the same menu, the confirmation was not displayed. Only when closing the window with the red button is the left corner triggers it.
It uses the [java.awt.Desktop API](https://docs.oracle.com/javase/9/docs/api/java/awt/Desktop.html) introduced in java 6 to make it works.
Here is what looks like the dialog box on the built in menu:
=> 💄 use java.awt.Desktop to enhance the user experience on mac os

src/main/java/com/marginallyclever/makelangelo/Makelangelo.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_Dragon_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_FibonacciSpiral_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_GosperCurve_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_HilbertCurve_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_KochCurve_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_LSystemTree_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_Lissajous_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_Maze_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_SierpinskiTriangle_Panel.java, src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_Spirograph_Panel.java, src/main/java/com/marginallyclever/makelangelo/turtle/turtleRenderer/TurtleRenderFactory.java, src/main/resources/languages/english.xml, src/main/resources/languages/french.xml
a try to resolve some elements in https://github.com/MarginallyClever/Makelangelo-software/issues/513
I am not satisfied with what I propose for the enum.
https://github.com/MarginallyClever/Makelangelo-software/blob/c4b369c1713061acd0302a6fd4fdc881b40fe1d7/src/main/java/com/marginallyclever/makelangelo/turtle/turtleRenderer/TurtleRenderFactory.java#L14-L17
As I want to ensure that the CI test identifies the keys, I need a Translator.get("...") with simple fixed String.
But that makes the encoding and/or the enum unpleasant to look at from a code point of view.
Any ideas for finding a better compromise? or I drop the guarantee of the control of the translation keys (and the fact of explaining in the enum which element is used for the translation keys and therefore in the event of …
=> New gui translated elements

src/main/java/com/marginallyclever/makelangelo/preview/PreviewPanel.java
When zooming in with the track pad, sometimes it zoom out and vice versa.
Here is a fix to ignore small movement in the reverse direction.
=> 🐛 fix zoom movement

src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/MakelangeloCustom.java
Before:
Now: 
for small robot:
for larger one:
[Fix #566](https://github.com/MarginallyClever/Makelangelo-software/issues/556)
=> 🐛 fix the position of the control board and lcd on small robot

src/main/java/com/marginallyclever/makelangelo/select/Select.java
Under linux Ubuntu ( 18.04 ? ) 
The default systeme LookAndFeel "com.sun.java.swing.plaf.gtk.GTKLookAndFeel" create a NPE on some Panel loading.
Using "-nolf" commande line argument is a way to avoid it but to be more user friendly ...
This is a "quick/bad fix" as it do not resolve the root issue.
But the LookAndFeel have other issues : like the tooltips font color is the same as the tooltips background color ...
=> Linux for some java lookandfeel bug fix

src/main/java/com/marginallyclever/makelangelo/makelangeloSettingsPanel/GFXPreferences.java, src/main/java/com/marginallyclever/makelangelo/preview/Camera.java, src/main/java/com/marginallyclever/makelangelo/preview/PreviewPanel.java, src/main/java/com/marginallyclever/makelangelo/select/SelectPanel.java, src/main/java/com/marginallyclever/makelangelo/select/SelectSpinner.java, src/main/resources/languages/english.xml, src/main/resources/languages/french.xml
When click + drag on the preview pane to move the preview, I need to move the mouse a lot.
Here is a new option to configure it. By default, the value is the same as today: `1`.
On my computer, I set it to 4 to have a good feeling.
=> 💄 Add an option to set a speed accelerator when dragging the preview

src/main/java/com/marginallyclever/communications/serial/SerialTransportLayer.java, src/test/java/com/marginallyclever/communications/SerialTransportLayerTest.java
Asked on discord by @Mieg : 
> I tried setting up a 'virtual' serial device on my macbook using socat, and that does work - but Makelangelo doesn't see it because the device name doesn't start with /dev/tty. or /dev/cu.
=> remove the filter for serial connections on mac to return all the values possible. Useful for socat.

src/main/java/com/marginallyclever/communications/serial/SerialTransportLayer.java, src/test/java/com/marginallyclever/communications/SerialTransportLayerTest.java
include only /dev/cu..* and /dev/ttys001 but not /dev/ttys1
=> reintroduce the filter for serial connections on mac to return more values

pom.xml, src/main/java/com/marginallyclever/makelangelo/makeart/imageconverter/Converter_IntensityToHeight.java, src/main/java/com/marginallyclever/makelangelo/makeart/imageconverter/Converter_QuadTreeInstant.java, src/main/java/com/marginallyclever/makelangelo/makeart/imageconverter/ImageConverterFactory.java, src/main/resources/languages/english.xml
* `maxDepth` maximum depth for the quad fractal.
* `baseCutOff`
* `cutOffIncrement` Depending on the depth of the subfractal, the cut-off level will change(the deeper you get into the fractal; the lower the cut off level), this variable determines the decrement.
Gives instant quad-tree-like fractal,
The implementation is based on recursion and doesn't save any boxes data, it draws the lines directly, in a smart manner that prevent drawing lines overlapping with parent fractal lines.
However, the whole implementation is based on my trust on the gcode converter to get rid of exact duplicate lines, otherwise it would be very inefficient for plotting, we could have a voice call for further details.
=> Quadtree-like instant filter
