- java/src/Makelangelo/Makelangelo.java
The hyperlinks in the about dialog were not clickable in my build, so I added a [JEditorPane](http://docs.oracle.com/javase/7/docs/api/javax/swing/JEditorPane.html) with a [HyperlinkListener](http://docs.oracle.com/javase/7/docs/api/javax/swing/event/HyperlinkListener.html) to allow them to be opened in a web browser.
In the preexisting HTML, I added an anchor tag to the email with mailto: and added my name and a link to my GitHub account.
> Added clickable links to About Dialog.

- java/src/Filters/Filter.java
> Close input stream using try-with-resources statement.

- java/src/Makelangelo/MainGUI.java
- java/src/Makelangelo/Makelangelo.java
- java/src/Makelangelo/MultilingualSupport.java
Made sure MultilingualSupport#ChooseLanguage() is called after MainGUI and MultilingualSupport #getSingleton()
Fixes #72
> Made sure MultilingualSupport#ChooseLanguage() is called after#getSingleton()

- java/src/main/java/com/marginallyclever/makelangelo/MachineConfiguration.java
The refactor/merge of [MachineConfiguration](https://github.com/MarginallyClever/Makelangelo/blob/dev/java/src/main/java/com/marginallyclever/makelangelo/MachineConfiguration.java) caused conflicts. This PR successfully resolves them.
> fix merge conflicts

- java/src/main/java/com/marginallyclever/makelangelo/MachineConfiguration.java
- java/src/main/java/com/marginallyclever/makelangelo/MainGUI.java
Sorry about #99, this should fix it for you.
> machine configuration availability regression fix

- java/languages/english.xml
- java/src/main/java/com/marginallyclever/makelangelo/MainGUI.java
- java/src/main/java/com/marginallyclever/makelangelo/MakelangeloDriveControls.java
Refer Issue #97 
Connect/Disconnect options added as placeholders for later additions
Only added to English translation so far
> Add Disengage Button

- last_official_release/Makelangelo/languages/portuguese.xml
- last_official_release/Makelangelo/languages/portuquese.xml
I've Created a portuguese language version for the Makelangelo
> Portuguese translation

- java/src/main/java/com/marginallyclever/makelangelo/MachineConfiguration.java
- java/src/main/java/com/marginallyclever/makelangelo/MainGUI.java
- java/src/main/java/com/marginallyclever/makelangelo/MultilingualSupport.java
- java/src/main/java/com/marginallyclever/makelangelo/PreferencesHelper.java
- java/src/main/java/com/marginallyclever/util/Ancestryable.java
- java/src/main/java/com/marginallyclever/util/MarginallyCleverPreferences.java
> Generic warning fixes.

- java/src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- java/src/main/java/com/marginallyclever/makelangelo/PropertiesFileHelper.java
I did some quick code cleanup.
> Minor housekeeping

- java/pom.xml
I [forked](https://github.com/virtuoushub/mavennatives) the [mavennatives plugin](https://code.google.com/p/mavennatives/) which adds the ability to easily bundle native dependencies in your Maven project. I configured it to be used with this Makelangelo project.
> Adding use of my natives plugin fork.

- java/pom.xml
Using update versions of the dependendencies where applicable.
> Using updated versions of some dependencies.

- java/src/main/java/com/marginallyclever/makelangelo/MakelangeloRobotPanel.java
> Issue 158 fix

- script/bootstrap
- script/callmavenwrapper
- script/test
> Update shebang to use bash instead of sh

- java/src/main/java/com/marginallyclever/communications/serial/SerialConnection.java
- java/src/main/java/com/marginallyclever/makelangeloRobot/MakelangeloRobot.java
Send M100 to robot so it can identify itself.
> Say hi to robot when establishing a new connection

- src/main/com/marginallyclever/communications/serial/SerialTransportLayer.java
Fix for issue discussed in [the forum](https://www.marginallyclever.com/learn/forum/topic/hc06-bluetooth-with-makelangelo-on-macos/#post-28208).
> List Bluetooth serial connections on MacOS.

- src/main/com/marginallyclever/makelangelo/Makelangelo.java
Like in Google Chrome, reset zoom with CMD+0.
> Reset zoom with keyboard shortcut.

- pom.xml
See https://bugs.openjdk.java.net/browse/JDK-8212233.
Now it builds without errors for me too.
> Fix javadoc error.

- src/main/com/marginallyclever/artPipeline/ArtPipeline.java
Hopefully it's acceptable this time. I've added more comments and changed a few variable names for clarity.
Real world drawing time of reorder_test.svg:
```
16m19s 13193 / 13193 100.00%
```
Compared to real world drawing time of reorder_test.svg, with algorithm currently implemented in dev:
```
19m51s 13004 / 13004 100.00%
```
> Reorder fix3

- src/main/com/marginallyclever/artPipeline/generators/Generator_Package.java
- src/main/com/marginallyclever/artPipeline/generators/Generator_Package_Panel.java
- src/main/resources/META-INF/services/com.marginallyclever.artPipeline.generators.ImageGenerator
Added a generator to create custom pacakge boxes for shipping. usually you cannot print them with your desktop printer,
because they are way too latrge.
Makelangelo is perfect for that.
> added generator for big parcel boxes

- src/main/com/marginallyclever/artPipeline/ArtPipeline.java
- src/main/com/marginallyclever/artPipeline/generators/Generator_GosperCurve.java
- src/main/com/marginallyclever/artPipeline/generators/Generator_HilbertCurve.java
- src/main/com/marginallyclever/artPipeline/loadAndSave/LoadAndSaveSVG.java
- src/main/com/marginallyclever/makelangeloRobot/MakelangeloRobotPanel.java
- src/main/com/marginallyclever/makelangeloRobot/settings/MakelangeloRobotSettings.java
- src/main/com/marginallyclever/makelangeloRobot/settings/PanelAdjustPaper.java
Added Rotation feature into Art Pipeline.
Also introduced "reference angle" else the picture would rotate  whenever artpipeline is called.
Undone some changes which are not neccessary anymore, [paper shift is in art pipeline now.
> Add paper shifts

- src/main/com/marginallyclever/artPipeline/generators/Generator_HilbertCurve.java
- src/main/com/marginallyclever/artPipeline/loadAndSave/LoadAndSaveSVG.java
- src/main/com/marginallyclever/convenience/Turtle.java
- src/main/com/marginallyclever/makelangeloRobot/MakelangeloRobot.java
- src/main/com/marginallyclever/makelangeloRobot/settings/MakelangeloRobotSettings.java
- src/main/com/marginallyclever/makelangeloRobot/settings/hardwareProperties/CartesianProperties.java
- src/main/com/marginallyclever/makelangeloRobot/settings/hardwareProperties/Makelangelo2Properties.java
- src/main/com/marginallyclever/makelangeloRobot/settings/hardwareProperties/Makelangelo5Properties.java
- src/main/com/marginallyclever/makelangeloRobot/settings/hardwareProperties/MakelangeloCustomProperties.java
- src/main/com/marginallyclever/makelangeloRobot/settings/hardwareProperties/MakelangeloHardwareProperties.java
- src/main/com/marginallyclever/makelangeloRobot/settings/hardwareProperties/ZarplotterProperties.java
Now moved my "special"  getHome() into MakelangeloCustomProperties
also made an abstract class for getGCodeConfig and filled in all the related  classes correctly.
> Customplotter

- src/main/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
- src/main/com/marginallyclever/makelangelo/plotter/plotterControls/SaveGCode.java
Hi,
I moved the "save gcode" button in the Makelangelo menu for direct access: 
Here is the updated plotter interface:
> Move the save to gcode button in the menu Makelangelo

- src/main/com/marginallyclever/makelangelo/makeArt/turtleGenerator/Generator_GosperCurve.java
> Generator_GosperCurve a PenDown

- src/main/com/marginallyclever/makelangelo/turtle/Turtle.java
Correction of two errors reported during its generation.
> build javadoc

- src/main/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_SpiralPulse_Panel.java
- src/main/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_Spiral_CMYK_Panel.java
- src/main/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_Spiral_Panel.java
- src/main/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_VoronoiZigZag_Panel.java
- src/main/resources/languages/english.xml
> Add missing translation

- src/main/java/com/marginallyclever/makelangelo/Translator.java
as @coliss86  pointed out to me, I am correcting it. (normally only tabs and no spaces for indentation ... but i have make the change manually as i can get my NetBeans to do it automatically on reformat selection Alt+Shift+f )
(It reminds me of an episode from https://en.wikipedia.org/wiki/Silicon_Valley_(TV_series) ;) )
> Code formating tabs and not spaces

- src/main/java/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_ColorBoxes.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_ColorFloodFill.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/imageConverter/ImageConverter.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/TurtleGenerator.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/turtleGenerator/TurtleGeneratorPanel.java
- src/main/java/com/marginallyclever/makelangelo/plotter/marlinSimulation/MarlinSimulation.java
- src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettings.java
No review just so javadoc can be build.
> javadoc build errors fix.

- .gitignore
- src/main/java/com/marginallyclever/convenience/log/Log.java
- src/main/java/com/marginallyclever/convenience/log/RollOncePerSessionTriggeringPolicy.java
- src/main/java/module-info.java
- src/main/resources/logback.xml
Thanks @PPAC37, here is fix for #408 where the previous log was deleted to early.
I also renamed the log file to `makelangelo.log` to make more clear which log come from where
> Fix #408: improve log rotation and crash detection

- src/main/java/com/marginallyclever/convenience/log/LogPanel.java
Following review comment: https://github.com/MarginallyClever/Makelangelo-software/pull/402#discussion_r775178467
> Rename okButton to copyClipboardButton in logPanel

- src/main/java/com/marginallyclever/makelangelo/CollapsiblePanel.java
Full expanded:
collapsed:
I'll use it for the plotter interface
> Resurrect collapsiblePanel

- src/main/java/com/marginallyclever/util/MarginallyCleverPreferencesHelper.java
- src/main/java/com/marginallyclever/util/PreferencesHelper.java
- src/test/java/com/marginallyclever/makelangelo/PreferencesHelperTest.java
- src/test/java/com/marginallyclever/makelangelo/TranslatorTests.java
Hi, 
here is a rewrite of the unit test of PreferencesHelperTest in order to understand how this component works and do something useful in this test.
Also some cleanup in PreferencesHelper.
> Rewrite unit test of PreferencesHelperTest

- .github/workflows/stale.yml
I forgot this workflow in #439
> Stale workflow only on the main repos

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/paper/Paper.java
Here a small refactor, I just discovered the `setSystemLookAndFeel()` method, so I moved the os detection for the menu bar here.
> Move macOS look and feel to setSystemLookAndFeel()

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/machines/Machines.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/Cartesian.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/Makelangelo3.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/Makelangelo3_3.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/Makelangelo5.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/MakelangeloCustom.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/PlotterRenderer.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterRenderer/Zarplotter.java
- src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettingsPanel.java
Load the machine type at startup and save it when selecting it in the Robot menu.
If the settings was never saved, the default machine is `MAKELANGELO_5`.
> Save and load machine style

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/paper/PaperSettings.java
- src/main/resources/languages/english.xml
I also changed `<->` to Landscape
> Add translation to paper settings and add missing translation to robot menu

- src/main/java/com/marginallyclever/makelangelo/plotter/Plotter.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/JogInterface.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
Must be merged after #447 and #449.
When opening the Robot control: 
When the button connect is clicked:
> Disable / enable the buttons in the advanced based on the connection status

- src/main/resources/languages/chinese.xml
- src/main/resources/languages/dutch.xml
- src/main/resources/languages/piglatin.xml
deleted key in https://github.com/MarginallyClever/Makelangelo-software/commit/0b01453acdacfffe4851bebf40dfc2a02357e61a
<key>SetHome</key>
<key>GoHome</key>
<key>FindHome</key>
<key>DisengageMotors</key>
<key>EngageMotors</key>
Or do we keep unused key  ?
> impacting deleted key in english.xml to other languages.

- src/main/resources/languages/chinese.xml
- src/main/resources/languages/dutch.xml
- src/main/resources/languages/english.xml
- src/main/resources/languages/german.xml
- src/main/resources/languages/piglatin.xml
https://github.com/MarginallyClever/Makelangelo-software/commit/b84463651e632d92a3d23fc73d62b864b2fa2626
```
<key>ChangeToolPrefix</key>
<value>Please prepare </value>
(key renamed and value changed) ->
<key>ChangeToolTitle</key>
<value>Change Pen</value>
--
<key>ChangeToolPostfix</key>
<value> and click any button to continue.</value>
(key renamed and value changed) ->
<key>ChangeToolMessage</key>
<value>Please change the pen to match this color.</value>
```
> Languages key renamed but value also change so to del in other lang

- src/main/resources/languages/chinese.xml
- src/main/resources/languages/dutch.xml
- src/main/resources/languages/german.xml
- src/main/resources/languages/piglatin.xml
Some key rename not impated in other languages .xml ( when renamed in englis.xml )
> Languages some corrections

- src/main/java/com/marginallyclever/convenience/ColorRGB.java
- src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettings.java
- src/test/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettingsTest.java
> Add unit test for PlotterSettings

- .github/workflows/maven.yml
- src/main/java/module-info.java
- src/test/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettingsTest.java
Associated doc: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
> Run the CI on pull request in order to get the status when reviewing it

- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/MarlinInterface.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
- src/main/resources/languages/english.xml
- src/test/java/com/marginallyclever/makelangelo/plotter/plotterControls/MarlinInterfaceTest.java
Here is the dialog when the printer says "home first":
> Add a dialog message when the printer says HomeXYFirst and when an error occurs

- src/main/java/com/marginallyclever/makelangelo/CollapsiblePanel.java
- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
The PlotterControls is resizable:
> 💄PlotterControls is now resizable again and panes within follow the size of the parent

- src/main/java/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_CMYK.java
- src/main/resources/languages/chinese.xml
- src/main/resources/languages/english.xml
- src/main/resources/languages/german.xml
Partial solutions for another ConverterCMYK issue.
as explaine in https://github.com/MarginallyClever/Makelangelo-software/issues/488#issuecomment-1025005938
> Fix converter cmyk.java passes value should not be lower than 1

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
Fix #501 
@i-make-robots  can you try this update please ? It may fix your issue
> 🐛 fix #501: check if the action is supported before registering handlers

- src/test/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettingsTest.java
This what I was trying to explain in https://github.com/MarginallyClever/Makelangelo-software/pull/481#discussion_r794288189
> ✅ Enhance PlotterSettingsTest

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/LoadFilePanel.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadDXF.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadGCode.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch2.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java
- src/main/java/com/marginallyclever/makelangelo/makelangeloSettingsPanel/MakelangeloSettingPanel.java
- src/main/java/com/marginallyclever/makelangelo/plotter/PiCaptureAction.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
- src/main/resources/languages/english.xml
#502 shows that some translation are missing, here is a fix
> 🐛 fixing missing translation

- src/test/java/com/marginallyclever/makelangelo/LanguagesXmlValidationForNoDupKeyTest.java
Bad IDE config ( was 8 space for a tab, now… set to 4 space for a tab.)
My apologies to @coliss86  for not understanding sooner.
> code indentation correction 

- src/test/java/com/marginallyclever/makelangelo/SelectGUITest.java
- src/test/java/com/marginallyclever/makelangelo/paper/PaperSettingsTest.java
- src/test/java/com/marginallyclever/makelangeloRobot/MakelangeloRobotPanelTest.java
The base code as changed recently which allow all the tests to be run
> ✅ Enable all tests

- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/ChooseConnection.java
Here is the look when no connection is found:
> 💄 disable the connection button if no connection is found

- src/main/resources/languages/german.xml
Many thanks for the translation work done on https://crowdin.com/project/marginallyclevermakelangelo-so by https://crowdin.com/profile/pgeilert
> language german xml update thanks to @keepthefunk#5098 on discord

- src/main/java/com/marginallyclever/convenience/ToggleButtonIcon.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/ChooseConnection.java
It replaces the `ButtonIcon bConnect` of `ChooseConnection` with the same functionality and allow this new button to be re-used elsewhere.
> 💄 add a button with multiple sets of icons, texts and optionally foreground colors

- src/main/java/com/marginallyclever/makelangelo/DialogAbout.java
- src/main/java/com/marginallyclever/makelangelo/DialogBadFirmwareVersion.java
- src/main/java/com/marginallyclever/makelangelo/select/SelectReadOnlyText.java
Surely a little more greedy but seems much more pleasant / generic and user friendly. 
what do you think?
> refactoring utility function in SelectReadOnlyText to create JeditoPane whith HyperLinkListenerAndToolTips

- src/main/java/com/marginallyclever/makelangelo/Translator.java
- src/main/java/com/marginallyclever/makelangelo/TranslatorLanguage.java
- src/test/resources/translator/language_no_dup_key.xsd
to fix CI test for https://github.com/MarginallyClever/Makelangelo-software/pull/530
> remove/fix language empty value restriction (xml validation and code TranslationLanguage)

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
> 🐛 load the plotter settings when starting the app

- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadSVG.java
as explaine in https://github.com/MarginallyClever/Makelangelo-software/issues/353#issuecomment-1039446478
avoid having some drawn lines which should be displacements.
> Fix for seahorse 

- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java
- src/main/java/com/marginallyclever/makelangelo/turtle/Turtle.java
> More resilient LoadScratch3 with some fix (orientation)

- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java
- src/main/resources/logback.xml
> Load scratch3 logger trace and not a boolean verbose

- src/main/java/com/marginallyclever/makelangelo/makeArt/imageConverter/Converter_Wander.java
> Converter Wander BW cumultation fix

- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/LoadScratch3.java
> fix_bad_fix point in direction (and some comments)

- src/main/java/com/marginallyclever/makelangelo/select/SelectColor.java
> JColorChooser.showDialog return null if cancel.

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/MakelangeloVersion.java
- src/main/java/com/marginallyclever/makelangelo/plotter/Plotter.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/SaveGCode.java
The details of the version in addition if DEV=true. ( JFrame title and .gcode Header)
> Version utility class for gcode comment and title in dev

- src/main/java/com/marginallyclever/communications/dummy/DummyTransportLayer.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/ChooseConnection.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/MarlinInterface.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/communications/DummyUI.java
Only available when "DEV" is true
screenshot:
This will allow to work on the communication withe the robot without needing one \o/
> 🧑‍💻Add dummy transport layer to ease development.

- src/main/java/com/marginallyclever/communications/dummy/DummyTransportLayer.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/CropTurtle.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/SaveDXF.java
- src/main/java/com/marginallyclever/makelangelo/makeArt/io/vector/SaveSVG.java
- src/main/java/com/marginallyclever/makelangelo/plotter/Plotter.java
- src/main/java/com/marginallyclever/makelangelo/plotter/marlinSimulation/MarlinSimulation.java
- src/main/java/com/marginallyclever/makelangelo/plotter/marlinSimulation/MarlinSimulationVisualizer.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/ChooseConnection.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/MarlinInterface.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/PlotterControls.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/SaveGCode.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plotterControls/communications/DummyUI.java
- src/main/java/com/marginallyclever/makelangelo/turtle/MovementType.java
- src/main/java/com/marginallyclever/makelangelo/turtle/Turtle.java
- src/main/java/com/marginallyclever/makelangelo/turtle/TurtleMove.java
- src/main/java/com/marginallyclever/makelangelo/turtle/turtleRenderer/TurtleRenderFacade.java
Must be merged after #589 
This refactoring will allow adding new type of movement for #580
> ♻️ Extract TurtleMove constants to Enum 

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
When opening a file, its filename is added to the title of the main window
> 💄 Add the filename in the title of the main window

- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
> 💄 prevent the PlotterSettingsPanel to be resizeable

- src/test/java/com/marginallyclever/makelangelo/plotter/plottercontrols/SaveGCodeTest.java
- src/test/resources/gcode/multi_shapes_ignatus2.gcode
- src/test/resources/gcode/multi_shapes_path-circle-line-rect.gcode
- src/test/resources/gcode/save_multi_colors-1.gcode
- src/test/resources/gcode/save_multi_colors-2.gcode
- src/test/resources/gcode/save_multi_colors.gcode
- src/test/resources/gcode/save_simple_move.gcode
> 🐛 Ignore makelangelo version in file comparison

- pom.xml
- src/main/java/com/marginallyclever/convenience/ButtonIcon.java
- src/main/java/com/marginallyclever/convenience/ToggleButtonIcon.java
- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plottercontrols/PlotterControls.java
- src/main/java/module-info.java
- src/main/resources/com/marginallyclever/makelangelo/FlatLightLaf.properties
New look and feel by using flatlaf : https://www.formdev.com/flatlaf/
The UI looks more modern and use native open / save dialog
Plotter Controls : 
Open / Save dialog
Popup have also an icon:
> 💄 Add flatlaf look n feel

- src/main/java/com/marginallyclever/makelangelo/plotter/plotterrenderer/MakelangeloCustom.java
> 💄 Reduce the size of the mounting plate for PCB

- src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettings.java
This is a start for implementing #580. @PPAC37 started it in #583 but he didn't finished it.
I talked to him on discord and he is OK that I finished its work. I'll split in few PR in order to improve review.
> ♻️ Extract constants of the PlotterSettings

- src/main/java/com/marginallyclever/communications/dummy/DummyTransportLayer.java
- src/main/java/com/marginallyclever/makelangelo/Makelangelo.java
- src/main/java/com/marginallyclever/makelangelo/makeart/io/SaveGCode.java
- src/main/java/com/marginallyclever/makelangelo/plotter/plottercontrols/PlotterControls.java
- src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettings.java
- src/main/java/com/marginallyclever/makelangelo/plotter/settings/PlotterSettingsUserGcodePanel.java
- src/main/java/com/marginallyclever/makelangelo/select/SelectTextArea.java
- src/main/resources/languages/english.xml
- src/main/resources/languages/french.xml
- src/test/java/com/marginallyclever/makelangelo/makeart/io/SaveGCodeTest.java
- src/test/resources/gcode/save_multi_colors-1.gcode
- src/test/resources/gcode/save_multi_colors-2.gcode
- src/test/resources/gcode/save_multi_colors.gcode
- src/test/resources/gcode/save_simple_move.gcode
- src/test/resources/gcode/save_subsection.gcode
this is based on the work of @PPAC37  on #583
> ✨ Add start / end gcode
